In [1]:
import pandas as pd
import os
import folium

In [2]:
folder = '/home/jibo16/Desktop/Hermes-storeLoc-Map/PrecipMap/Datak/7890488'

filelist = [file for file in os.listdir(folder) if file.endswith('csv')]


for file in filelist:
    '''
    This iteration converts csv's to df's and gives the df the same name as the csv file
    '''
    exec("%s = pd.read_csv('%s',on_bad_lines='skip')" % (file.split('.')[0], os.path.join(folder,file)))

In [3]:
USW00014929.isna().sum()

Unnamed: 0      0
Date            0
tmax          551
tmin          587
prcp          687
dtype: int64

In [4]:
USW00014925.isna().sum()

Unnamed: 0        0
Date              0
tmax           9558
tmin           9590
prcp          10109
dtype: int64

In [5]:
for file in filelist:
    exec("print(file)")

city_info.csv
USW00094973.csv
USW00094950.csv
USW00094949.csv
USW00094929.csv
USW00094910.csv
USW00094908.csv
USW00094860.csv
USW00094850.csv
USW00094847.csv
USW00094846.csv
USW00094830.csv
USW00094823.csv
USW00094822.csv
USW00094815.csv
USW00094746.csv
USW00094728.csv
USW00094298.csv
USW00094236.csv
USW00094224.csv
USW00094129.csv
USW00094040.csv
USW00094014.csv
USW00094012.csv
USW00094008.csv
USW00093988.csv
USW00093874.csv
USW00093842.csv
USW00093824.csv
USW00093822.csv
USW00093821.csv
USW00093820.csv
USW00093819.csv
USW00093817.csv
USW00093815.csv
USW00093812.csv
USW00093805.csv
USW00093729.csv
USW00093721.csv
USW00093193.csv
USW00093134.csv
USW00093058.csv
USW00093037.csv
USW00053920.csv
USW00024286.csv
USW00024257.csv
USW00024233.csv
USW00024232.csv
USW00024221.csv
USW00024213.csv
USW00024163.csv
USW00024157.csv
USW00024155.csv
USW00024153.csv
USW00024149.csv
USW00024144.csv
USW00024143.csv
USW00024131.csv
USW00024128.csv
USW00024127.csv
USW00024121.csv
USW00024032.csv
USW00024028.csv
USW00024023.csv
USW00024021.csv
USW00024018.csv
USW00024011.csv
USW00023275.csv
USW00023271.csv
USW00023188.csv
USW00023185.csv
USW00023183.csv
USW00023179.csv
USW00023160.csv
USW00023155.csv
USW00023154.csv
USW00023066.csv
USW00023065.csv
USW00023051.csv
USW00023050.csv
USW00023047.csv
USW00023044.csv
USW00023009.csv
USW00014991.csv
USW00014990.csv
USW00014972.csv
USW00014944.csv
USW00014943.csv
USW00014942.csv
USW00014941.csv
USW00014939.csv
USW00014936.csv
USW00014935.csv
USW00014933.csv
USW00014929.csv
USW00014926.csv
USW00014925.csv
USW00014923.csv
USW00014922.csv
USW00014920.csv
USW00014918.csv
USW00014916.csv
USW00014914.csv
USW00014913.csv
USW00014898.csv
USW00014897.csv
USW00014895.csv
USW00014894.csv
USW00014860.csv
USW00014848.csv
USW00014847.csv
USW00014845.csv
USW00014842.csv
USW00014840.csv
USW00014839.csv
USW00014837.csv
USW00014836.csv
USW00014827.csv
USW00014821.csv
USW00014792.csv
USW00014778.csv
USW00014768.csv
USW00014764.csv
USW00014753.csv
USW00014750.csv
USW00014745.csv
USW00014742.csv
USW00014739.csv
USW00014735.csv
USW00014733.csv
USW00014711.csv
USW00014710.csv
USW00013996.csv
USW00013995.csv
USW00013994.csv
USW00013985.csv
USW00013984.csv
USW00013971.csv
USW00013970.csv
USW00013968.csv
USW00013967.csv
USW00013964.csv
USW00013963.csv
USW00013962.csv
USW00013958.csv
USW00013957.csv
USW00013942.csv
USW00013899.csv
USW00013897.csv
USW00013896.csv
USW00013895.csv
USW00013893.csv
USW00013889.csv
USW00013886.csv
USW00013883.csv
USW00013882.csv
USW00013881.csv
USW00013876.csv
USW00013874.csv
USW00013873.csv
USW00013866.csv
USW00013865.csv
USW00013838.csv
USW00013833.csv
USW00013781.csv
USW00013743.csv
USW00013740.csv
USW00013739.csv
USW00013737.csv
USW00013736.csv
USW00013733.csv
USW00013722.csv
USW00012960.csv
USW00012924.csv
USW00012923.csv
USW00012921.csv
USW00012844.csv
USW00012842.csv
USW00012839.csv
USW00012836.csv
USW00012835.csv
USW00012816.csv
USW00012815.csv
USW00004853.csv
USW00003965.csv
USW00003963.csv
USW00003953.csv
USW00003947.csv
USW00003945.csv
USW00003940.csv
USW00003937.csv
USW00003927.csv
USW00003904.csv
USW00003872.csv
USW00003860.csv
USW00003859.csv
USW00003856.csv
USW00003822.csv
USW00003820.csv
USW00003813.csv
USW00003812.csv
USW00003171.csv
USW00003145.csv
USW00003103.csv
USW00003017.csv
USC00380072.csv
USC00356749.csv
USC00286055.csv
USC00280734.csv
USC00166584.csv
USC00042863.csv

In [6]:
sheets=[]    
for var in dir():
    if isinstance(locals()[var], pd.core.frame.DataFrame):
        print(locals()[var])

       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  60.0  41.0  0.00
1               2  1894-01-02  58.0  50.0  0.40
2               3  1894-01-03  57.0  42.0  0.00
3               4  1894-01-04  53.0  42.0  0.28
4               5  1894-01-05  50.0  38.0  0.00
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27   NaN   NaN   NaN
46747       46748  2021-12-28   NaN   NaN   NaN
46748       46749  2021-12-29   NaN   NaN   NaN
46749       46750  2021-12-30   NaN   NaN   NaN
46750       46751  2021-12-31   NaN   NaN   NaN

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  63.0  31.0  0.00
1               2  1894-01-02  70.0  36.0  0.00
2               3  1894-01-03  71.0  42.0  0.00
3               4  1894-01-04  74.0  44.0  0.23
4               5  1894-01-05  76.0  52.0  0.57
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27   NaN   NaN   NaN
46747       46748  2021-12-28   NaN   NaN  0.00
46748       46749  2021-12-29   NaN   NaN  0.03
46749       46750  2021-12-30   NaN   NaN  0.00
46750       46751  2021-12-31  84.0  62.1  0.00

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  44.0  21.0  0.00
1               2  1893-01-02  42.0  25.0  0.00
2               3  1893-01-03  38.0   NaN  0.00
3               4  1893-01-04   NaN  10.0  0.00
4               5  1893-01-05  21.0  12.0  0.56
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  52.0  24.1  0.00
47112       47113  2021-12-28  36.0  26.1  0.15
47113       47114  2021-12-29  42.1  26.1  0.31
47114       47115  2021-12-30  43.0  27.0  0.05
47115       47116  2021-12-31  46.9  39.0  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  53.0  25.0  1.17
1               2  1893-01-02  42.0  34.0  0.00
2               3  1893-01-03  36.0  21.0  0.00
3               4  1893-01-04  24.0  11.0  0.00
4               5  1893-01-05  24.0  17.0  0.19
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  53.1  28.0  0.00
47112       47113  2021-12-28   NaN   NaN  0.12
47113       47114  2021-12-29  46.9  37.0  0.21
47114       47115  2021-12-30  45.0  42.1  0.15
47115       47116  2021-12-31  53.1  44.1  0.03

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1875-01-01  52.0  43.0  0.68
1               2  1875-01-02  53.0  43.0  0.07
2               3  1875-01-03  46.0  37.0  0.00
3               4  1875-01-04  44.0  37.0  0.02
4               5  1875-01-05  39.0  32.0  0.13
...           ...         ...   ...   ...   ...
53686       53687  2021-12-27  32.0  24.1   NaN
53687       53688  2021-12-28  34.0  28.9  0.21
53688       53689  2021-12-29   NaN   NaN   NaN
53689       53690  2021-12-30   NaN   NaN   NaN
53690       53691  2021-12-31   NaN   NaN   NaN

[53691 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  60.0  42.0  0.35
1               2  1893-01-02  51.0  37.0  0.00
2               3  1893-01-03  50.0  35.0  0.00
3               4  1893-01-04  52.0  34.0  0.00
4               5  1893-01-05  51.0  29.0  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27   NaN   NaN   NaN
47112       47113  2021-12-28  75.9   NaN  0.00
47113       47114  2021-12-29   NaN   NaN   NaN
47114       47115  2021-12-30  77.0  62.1  1.00
47115       47116  2021-12-31   NaN   NaN   NaN

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1872-01-01  48.0  28.0  0.00
1               2  1872-01-02  43.0  28.0  0.00
2               3  1872-01-03  47.0  25.0  0.00
3               4  1872-01-04  39.0  22.0  0.00
4               5  1872-01-05  37.0  15.0  0.03
...           ...         ...   ...   ...   ...
54782       54783  2021-12-27  48.0  10.2  0.00
54783       54784  2021-12-28  33.1  15.3  0.00
54784       54785  2021-12-29  33.1  11.1  0.00
54785       54786  2021-12-30  48.9  15.3  0.00
54786       54787  2021-12-31  39.0   9.0  0.12

[54787 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1899-01-01  45.0   4.0  0.00
1               2  1899-01-02  41.0  19.0  0.00
2               3  1899-01-03  34.0  24.0  0.06
3               4  1899-01-04  32.0   4.0  0.00
4               5  1899-01-05  28.0   0.0  0.00
...           ...         ...   ...   ...   ...
44920       44921  2021-12-27  31.1  26.2  0.01
44921       44922  2021-12-28  27.1  22.1  0.43
44922       44923  2021-12-29  27.1  24.3  0.24
44923       44924  2021-12-30  32.0  24.1  0.05
44924       44925  2021-12-31  35.1  28.9  0.30

[44925 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1876-01-01   NaN   NaN  0.00
1               2  1876-01-02   NaN   NaN  0.00
2               3  1876-01-03   NaN   NaN  0.00
3               4  1876-01-04   NaN   NaN  0.00
4               5  1876-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
53321       53322  2021-12-27  57.9  46.0  0.00
53322       53323  2021-12-28  64.0  43.0  0.00
53323       53324  2021-12-29  63.0  39.9  0.00
53324       53325  2021-12-30  66.0  46.0  0.00
53325       53326  2021-12-31  63.0  52.0  0.11

[53326 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  77.0  42.0  0.00
1               2  1893-01-02  78.0  45.0  0.00
2               3  1893-01-03  81.0  41.0  0.00
3               4  1893-01-04  76.0  40.0  0.00
4               5  1893-01-05  85.0  41.0  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  52.0  37.9  0.31
47112       47113  2021-12-28  51.1  42.1  0.02
47113       47114  2021-12-29  53.1  42.1  0.04
47114       47115  2021-12-30  60.1  46.0  0.05
47115       47116  2021-12-31  61.0  43.0  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1870-01-01   NaN   NaN  0.00
1               2  1870-01-02   NaN   NaN  0.60
2               3  1870-01-03   NaN   NaN  0.00
3               4  1870-01-04   NaN   NaN  0.20
4               5  1870-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
55512       55513  2021-12-27  71.1  36.0  0.00
55513       55514  2021-12-28  68.0  41.0  0.00
55514       55515  2021-12-29  66.9  59.0  0.11
55515       55516  2021-12-30  64.0  50.0  0.13
55516       55517  2021-12-31  66.0  46.0  0.00

[55517 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01   NaN   NaN   NaN
1               2  1893-01-02   NaN   NaN   NaN
2               3  1893-01-03   NaN   NaN   NaN
3               4  1893-01-04   NaN   NaN   NaN
4               5  1893-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  73.9  51.1  0.00
47112       47113  2021-12-28  79.0  62.1  0.00
47113       47114  2021-12-29  79.0  66.9  0.08
47114       47115  2021-12-30  82.9  63.0  0.54
47115       47116  2021-12-31  81.0  60.1  0.07

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1872-01-01   NaN   NaN  0.00
1               2  1872-01-02   NaN   NaN  0.00
2               3  1872-01-03   NaN   NaN  0.12
3               4  1872-01-04   NaN   NaN  0.01
4               5  1872-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
54782       54783  2021-12-27  75.0  50.0  0.00
54783       54784  2021-12-28  79.0  64.0  0.00
54784       54785  2021-12-29  81.0  64.9  0.01
54785       54786  2021-12-30  73.0  61.0  1.05
54786       54787  2021-12-31  77.0  53.1  0.00

[54787 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01   NaN   NaN  0.00
1               2  1871-01-02   NaN   NaN  0.00
2               3  1871-01-03   NaN   NaN  0.00
3               4  1871-01-04   NaN   NaN  0.00
4               5  1871-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  77.0  55.9  0.00
55148       55149  2021-12-28  79.0  60.1  0.00
55149       55150  2021-12-29  79.0  60.1  0.00
55150       55151  2021-12-30  80.1  64.9  0.01
55151       55152  2021-12-31  81.0  66.9  0.00

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01  40.0   2.0  0.00
1               2  1895-01-02  39.0  12.0  0.00
2               3  1895-01-03  40.0  20.0  0.00
3               4  1895-01-04  39.0  28.0  0.00
4               5  1895-01-05  46.0  25.0  0.00
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  69.1  57.9  0.00
46382       46383  2021-12-28  73.9  63.0  0.28
46383       46384  2021-12-29  66.9  60.1  1.38
46384       46385  2021-12-30  69.1  52.0  0.00
46385       46386  2021-12-31  72.0  54.0  0.05

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1892-01-01   NaN   NaN   NaN
1               2  1892-01-02   NaN   NaN   NaN
2               3  1892-01-03   NaN   NaN   NaN
3               4  1892-01-04   NaN   NaN   NaN
4               5  1892-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
47477       47478  2021-12-27  59.0  44.1  0.00
47478       47479  2021-12-28  64.0  48.9  0.11
47479       47480  2021-12-29  61.0  48.9  0.23
47480       47481  2021-12-30  55.0  48.9  0.03
47481       47482  2021-12-31  59.0  43.0  0.03

[47482 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1892-01-01  56.0  32.0  0.00
1               2  1892-01-02  62.0  32.0  0.00
2               3  1892-01-03  33.0  17.0  0.15
3               4  1892-01-04  26.0  17.0  0.00
4               5  1892-01-05  35.0  25.0  0.25
...           ...         ...   ...   ...   ...
47477       47478  2021-12-27  69.1  45.0  0.20
47478       47479  2021-12-28  64.9  46.9  0.05
47479       47480  2021-12-29  62.1  51.1  0.11
47480       47481  2021-12-30  59.0  42.1  0.00
47481       47482  2021-12-31  62.1  39.0  0.00

[47482 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01   NaN   NaN  0.00
1               2  1894-01-02   NaN   NaN  0.00
2               3  1894-01-03   NaN   NaN  0.00
3               4  1894-01-04   NaN   NaN  0.00
4               5  1894-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27  61.0  44.1  0.00
46747       46748  2021-12-28  64.0  46.9  0.14
46748       46749  2021-12-29  63.0  48.9  0.57
46749       46750  2021-12-30  55.0  46.9  0.01
46750       46751  2021-12-31  59.0  42.1  0.02

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1883-01-01   NaN   NaN   NaN
1               2  1883-01-02   NaN   NaN   NaN
2               3  1883-01-03   NaN   NaN   NaN
3               4  1883-01-04   NaN   NaN   NaN
4               5  1883-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
50764       50765  2021-12-27  81.0  69.1   0.0
50765       50766  2021-12-28  79.0  66.0   0.0
50766       50767  2021-12-29  82.0  64.9   0.0
50767       50768  2021-12-30  81.0  57.9   0.0
50768       50769  2021-12-31  82.9  64.0   0.0

[50769 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1899-01-01  40.0  14.0  0.00
1               2  1899-01-02  49.0  16.0  0.00
2               3  1899-01-03  65.0  25.0  0.00
3               4  1899-01-04  70.0  47.0  0.13
4               5  1899-01-05  42.0  34.0  0.47
...           ...         ...   ...   ...   ...
44920       44921  2021-12-27  80.1  62.1  0.00
44921       44922  2021-12-28  81.0  57.0  0.00
44922       44923  2021-12-29  73.9  54.0  0.15
44923       44924  2021-12-30  75.0  48.0  0.00
44924       44925  2021-12-31  72.0  52.0  0.00

[44925 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01  56.0  44.0  0.00
1               2  1895-01-02  62.0  30.0  0.00
2               3  1895-01-03  60.0  38.0  1.50
3               4  1895-01-04  64.0  42.0  0.00
4               5  1895-01-05  70.0  54.0  0.00
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  78.1  61.0  0.00
46382       46383  2021-12-28  79.0  62.1  0.01
46383       46384  2021-12-29  80.1  71.1  0.00
46384       46385  2021-12-30  81.0  66.0  0.00
46385       46386  2021-12-31  80.1  73.0  0.00

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1896-01-01  50.0  22.0  0.00
1               2  1896-01-02  50.0  25.0  0.00
2               3  1896-01-03  61.0  40.0  0.00
3               4  1896-01-04  44.0  20.0  0.00
4               5  1896-01-05  32.0  16.0  0.00
...           ...         ...   ...   ...   ...
46016       46017  2021-12-27  80.1  64.9  0.00
46017       46018  2021-12-28  79.0  63.0  0.26
46018       46019  2021-12-29  82.0  68.0  0.00
46019       46020  2021-12-30  80.1  63.0  0.02
46020       46021  2021-12-31  82.9  64.9  0.00

[46021 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1890-01-01  52.0  41.0  0.23
1               2  1890-01-02  50.0  24.0  0.00
2               3  1890-01-03  43.0  20.0  0.00
3               4  1890-01-04  52.0  36.0  0.02
4               5  1890-01-05  62.0  39.0  0.62
...           ...         ...   ...   ...   ...
48207       48208  2021-12-27  63.0  39.9  0.00
48208       48209  2021-12-28  48.9  37.9  1.53
48209       48210  2021-12-29  39.0  33.1  0.01
48210       48211  2021-12-30  43.0  33.1  0.00
48211       48212  2021-12-31  63.0  34.0  0.00

[48212 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1889-01-01  44.0  19.0  0.00
1               2  1889-01-02  48.0  28.0  0.00
2               3  1889-01-03  52.0  33.0  0.00
3               4  1889-01-04  42.0  31.0  0.00
4               5  1889-01-05  30.0  25.0  0.00
...           ...         ...   ...   ...   ...
48572       48573  2021-12-27  64.0  39.0  0.00
48573       48574  2021-12-28  57.0  23.2  0.31
48574       48575  2021-12-29  33.1  19.2  0.00
48575       48576  2021-12-30  44.1  28.2  0.00
48576       48577  2021-12-31  54.0  30.9  0.00

[48577 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1891-01-01   NaN   NaN   NaN
1               2  1891-01-02   NaN   NaN   NaN
2               3  1891-01-03   NaN   NaN   NaN
3               4  1891-01-04   NaN   NaN   NaN
4               5  1891-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
47842       47843  2021-12-27  70.0  57.0  0.00
47843       47844  2021-12-28  71.1  54.0  0.12
47844       47845  2021-12-29  57.9  48.9  0.22
47845       47846  2021-12-30  55.9  48.0  0.00
47846       47847  2021-12-31  70.0  51.1  0.00

[47847 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01  37.0  17.0  0.00
1               2  1895-01-02  40.0  30.0  0.10
2               3  1895-01-03  36.0  27.0  0.00
3               4  1895-01-04  30.0  12.0  0.00
4               5  1895-01-05  39.0  30.0  0.00
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  66.0  43.0  0.00
46382       46383  2021-12-28  53.1  39.0  1.95
46383       46384  2021-12-29  44.1  34.0  0.00
46384       46385  2021-12-30  46.9  33.1  0.00
46385       46386  2021-12-31  66.0  32.0  0.00

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  46.0  22.0  0.00
1               2  1893-01-02  49.0  27.0  0.00
2               3  1893-01-03  57.0  25.0  0.00
3               4  1893-01-04  58.0  34.0  0.00
4               5  1893-01-05  45.0  36.0  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  66.9  39.9  0.00
47112       47113  2021-12-28  72.0  37.9  0.19
47113       47114  2021-12-29  53.1  31.1  0.00
47114       47115  2021-12-30  60.1  28.0  0.00
47115       47116  2021-12-31  69.1  46.0  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01  37.0  28.0  0.00
1               2  1871-01-02  40.0  22.0  0.00
2               3  1871-01-03  24.0  17.0  0.01
3               4  1871-01-04  31.0  10.0  0.00
4               5  1871-01-05  50.0   NaN  0.00
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  54.0  36.0  0.14
55148       55149  2021-12-28  44.1  36.0  0.21
55149       55150  2021-12-29  44.1  37.0  0.00
55150       55151  2021-12-30  42.1  39.0  0.00
55151       55152  2021-12-31   NaN   NaN   NaN

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1892-01-01  76.0  60.0  0.00
1               2  1892-01-02  71.0  54.0  0.53
2               3  1892-01-03  54.0  38.0  0.00
3               4  1892-01-04  61.0  35.0  0.00
4               5  1892-01-05  71.0  47.0  0.00
...           ...         ...   ...   ...   ...
47477       47478  2021-12-27  80.1  57.0  0.00
47478       47479  2021-12-28  81.0  57.9  0.00
47479       47480  2021-12-29  82.9  60.1  0.00
47480       47481  2021-12-30  82.0  62.1  0.00
47481       47482  2021-12-31  84.0  62.1  0.00

[47482 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1891-01-01   NaN   NaN   NaN
1               2  1891-01-02   NaN   NaN   NaN
2               3  1891-01-03   NaN   NaN   NaN
3               4  1891-01-04   NaN   NaN   NaN
4               5  1891-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
47842       47843  2021-12-27  78.1  54.0   0.0
47843       47844  2021-12-28  80.1  53.1   0.0
47844       47845  2021-12-29  82.0  53.1   0.0
47845       47846  2021-12-30  80.1  63.0   0.0
47846       47847  2021-12-31  79.0  64.9   0.0

[47847 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1892-01-01  78.0  56.0   0.0
1               2  1892-01-02  73.0   NaN   0.0
2               3  1892-01-03   NaN  44.0   0.0
3               4  1892-01-04  60.0  39.0   0.0
4               5  1892-01-05  68.0  37.0   0.0
...           ...         ...   ...   ...   ...
47477       47478  2021-12-27  81.0  60.1   0.0
47478       47479  2021-12-28  82.0  61.0   0.0
47479       47480  2021-12-29  82.9  62.1   0.0
47480       47481  2021-12-30  84.0  62.1   0.0
47481       47482  2021-12-31  84.0  66.9   0.0

[47482 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01   NaN   NaN  0.00
1               2  1871-01-02   NaN   NaN  0.00
2               3  1871-01-03   NaN   NaN  0.00
3               4  1871-01-04   NaN   NaN  0.02
4               5  1871-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  80.1  70.0  0.00
55148       55149  2021-12-28  79.0  71.1  0.00
55149       55150  2021-12-29  80.1  75.0  0.00
55150       55151  2021-12-30  82.0  75.0  0.00
55151       55152  2021-12-31  81.0  75.0  0.00

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1896-01-01  65.0  40.0   0.0
1               2  1896-01-02  71.0  50.0   0.0
2               3  1896-01-03  72.0  60.0   0.0
3               4  1896-01-04  67.0  52.0   0.0
4               5  1896-01-05  71.0  46.0   0.0
...           ...         ...   ...   ...   ...
46016       46017  2021-12-27  82.9  66.0   0.0
46017       46018  2021-12-28  79.0  66.0   0.0
46018       46019  2021-12-29  81.0  69.1   0.0
46019       46020  2021-12-30  82.9  69.1   0.0
46020       46021  2021-12-31  82.0  68.0   0.0

[46021 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1891-01-01  73.0  49.0   0.0

       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  54.0  42.0   NaN
1               2  1893-01-02  62.0  37.0   NaN
2               3  1893-01-03  57.0  40.0   NaN
3               4  1893-01-04  66.0  34.0   NaN
4               5  1893-01-05  64.0  44.0   NaN
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  79.0  63.0  0.00
47112       47113  2021-12-28  80.1  66.9  0.17
47113       47114  2021-12-29  82.9  70.0  0.00
47114       47115  2021-12-30  82.0  69.1  0.02
47115       47116  2021-12-31  84.0  72.0  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1892-01-01  66.0  26.0  1.40
1               2  1892-01-02  37.0  21.0  0.00
2               3  1892-01-03  51.0  19.0  0.00
3               4  1892-01-04  59.0  45.0  0.00
4               5  1892-01-05  47.0  31.0  0.00
...           ...         ...   ...   ...   ...
47477       47478  2021-12-27  70.0  51.1  0.00
47478       47479  2021-12-28  70.0  46.0  0.02
47479       47480  2021-12-29  51.1  39.9  0.09
47480       47481  2021-12-30  68.0  36.0  0.00
47481       47482  2021-12-31  73.9  48.9  0.25

[47482 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1886-01-01  36.0  25.0  0.00
1               2  1886-01-02  29.0  18.0  0.06
2               3  1886-01-03  21.0  16.0  0.01
3               4  1886-01-04  31.0  17.0  0.01
4               5  1886-01-05  32.0  12.0  0.00
...           ...         ...   ...   ...   ...
49668       49669  2021-12-27  45.0  30.2  0.00
49669       49670  2021-12-28  46.9  17.2  0.00
49670       49671  2021-12-29  32.0  15.3  0.00
49671       49672  2021-12-30  44.1  24.3  0.00
49672       49673  2021-12-31  37.0  16.0  0.00

[49673 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1875-01-01  38.0   9.0  0.01
1               2  1875-01-02  29.0  -6.0  0.00
2               3  1875-01-03   6.0   0.0  0.00
3               4  1875-01-04   4.0  -9.0  0.00
4               5  1875-01-05  10.0 -15.0  0.00
...           ...         ...   ...   ...   ...
53686       53687  2021-12-27  48.9  22.1  0.00
53687       53688  2021-12-28  50.0  18.1  0.00
53688       53689  2021-12-29  39.0  13.1  0.00
53689       53690  2021-12-30  60.1  10.2  0.00
53690       53691  2021-12-31  55.9  19.0  0.00

[53691 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  32.0  26.0  0.00
1               2  1893-01-02  33.0   NaN  0.00
2               3  1893-01-03   NaN   6.0  0.10
3               4  1893-01-04  34.0  18.0  0.00
4               5  1893-01-05  37.0  14.0  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  64.0  44.1  0.00
47112       47113  2021-12-28  46.9  39.0  1.08
47113       47114  2021-12-29  44.1  35.1  0.05
47114       47115  2021-12-30  50.0  37.0  0.01
47115       47116  2021-12-31  68.0  41.0  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1888-01-01  25.0   8.0  0.00
1               2  1888-01-02  48.0  18.0  0.00
2               3  1888-01-03  58.0  25.0  0.00
3               4  1888-01-04  68.0  44.0  0.00
4               5  1888-01-05  62.0  48.0  0.08
...           ...         ...   ...   ...   ...
48938       48939  2021-12-27  66.9  48.0  0.00
48939       48940  2021-12-28  64.9  43.0  0.43
48940       48941  2021-12-29  52.0  43.0  0.09
48941       48942  2021-12-30  57.9  39.0  0.00
48942       48943  2021-12-31  66.0  42.1  0.08

[48943 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1888-01-01  19.0   6.0  0.00
1               2  1888-01-02  41.0   9.0  0.00
2               3  1888-01-03  51.0  17.0  0.00
3               4  1888-01-04  51.0  27.0  0.00
4               5  1888-01-05  34.0  25.0  0.11
...           ...         ...   ...   ...   ...
48938       48939  2021-12-27  63.0  37.9  0.00
48939       48940  2021-12-28  60.1  22.1  0.05
48940       48941  2021-12-29  36.0  19.2  0.00
48941       48942  2021-12-30  46.9  28.2  0.00
48942       48943  2021-12-31  61.0  27.0  0.00

[48943 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1886-01-01  47.0  34.0  0.00
1               2  1886-01-02  48.0  29.0  0.00
2               3  1886-01-03  43.0  32.0  0.00
3               4  1886-01-04  48.0  34.0  0.00
4               5  1886-01-05  53.0   NaN  1.20
...           ...         ...   ...   ...   ...
49668       49669  2021-12-27  32.0  27.1  0.00
49669       49670  2021-12-28  42.1  30.2  0.05
49670       49671  2021-12-29  39.9  32.0  0.01
49671       49672  2021-12-30  39.0  35.1  0.01
49672       49673  2021-12-31  39.9  36.0  0.02

[49673 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1889-01-01  42.0  34.0  0.00
1               2  1889-01-02  40.0  30.0  0.00
2               3  1889-01-03  46.0  25.0  0.00
3               4  1889-01-04  48.0  26.0  0.00
4               5  1889-01-05  41.0  34.0  0.34
...           ...         ...   ...   ...   ...
48572       48573  2021-12-27  37.9  29.1  0.20
48573       48574  2021-12-28  43.0  33.1  0.00
48574       48575  2021-12-29  51.1  39.0  0.05
48575       48576  2021-12-30  51.1  43.0  0.08
48576       48577  2021-12-31  54.0  46.0  0.00

[48577 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01   NaN   NaN  0.01
1               2  1871-01-02   NaN   NaN  0.00
2               3  1871-01-03   NaN   NaN  0.01
3               4  1871-01-04   NaN   NaN  0.00
4               5  1871-01-05   NaN   NaN  0.01
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  41.0  28.2  0.05
55148       55149  2021-12-28  42.1  34.0  0.10
55149       55150  2021-12-29  41.0  34.0  0.04
55150       55151  2021-12-30  42.1  37.0  0.00
55151       55152  2021-12-31  46.9  37.0  0.01

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1874-01-01  37.0  24.0  0.00
1               2  1874-01-02  41.0  28.0  0.06
2               3  1874-01-03  47.0  35.0  0.00
3               4  1874-01-04  57.0  45.0  0.00
4               5  1874-01-05  57.0  25.0  0.14
...           ...         ...   ...   ...   ...
54051       54052  2021-12-27  34.0  26.2  0.00
54052       54053  2021-12-28  46.0  31.1  0.05
54053       54054  2021-12-29  37.9  33.1  0.01
54054       54055  2021-12-30  44.1  35.1  0.01
54055       54056  2021-12-31  46.9  37.9  0.08

[54056 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1872-01-01   NaN   NaN  0.00
1               2  1872-01-02   NaN   NaN  0.00
2               3  1872-01-03   NaN   NaN  0.00
3               4  1872-01-04   NaN   NaN  0.73
4               5  1872-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
54782       54783  2021-12-27  35.1  30.2  0.00
54783       54784  2021-12-28  46.0  33.1  0.04
54784       54785  2021-12-29  42.1  36.0  0.00
54785       54786  2021-12-30  42.1  37.9  0.06
54786       54787  2021-12-31  46.0  39.9  0.00

[54787 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1884-01-01  22.0  11.0  0.18
1               2  1884-01-02  30.0  14.0  0.38
2               3  1884-01-03  28.0   NaN  0.02
3               4  1884-01-04  12.0   6.0  0.00
4               5  1884-01-05  10.0  -4.0  0.00
...           ...         ...   ...   ...   ...
50399       50400  2021-12-27  29.1  22.1  0.00
50400       50401  2021-12-28  37.0  25.2  0.03
50401       50402  2021-12-29  33.1  29.1  0.00
50402       50403  2021-12-30  39.9  29.1  0.00
50403       50404  2021-12-31  37.9  30.9  0.04

[50404 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1868-01-01   NaN   NaN  0.70
1               2  1868-01-02   NaN   NaN  0.00
2               3  1868-01-03   NaN   NaN  0.00
3               4  1868-01-04   NaN   NaN  0.17
4               5  1868-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
56243       56244  2021-12-27  31.1  21.2  0.00
56244       56245  2021-12-28  37.9  26.2  0.04
56245       56246  2021-12-29  39.0  27.1  0.01
56246       56247  2021-12-30  37.0  32.0  0.04
56247       56248  2021-12-31  39.0  33.1  0.02

[56248 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  31.0   7.0  0.40
1               2  1893-01-02  39.0  27.0   NaN
2               3  1893-01-03  28.0   2.0   NaN
3               4  1893-01-04  15.0  -6.0   NaN
4               5  1893-01-05  21.0   7.0   NaN
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  31.1  24.3  0.01
47112       47113  2021-12-28  37.0  24.3  0.00
47113       47114  2021-12-29  35.1  29.1  0.00
47114       47115  2021-12-30  37.9  32.0  0.01
47115       47116  2021-12-31  37.9  33.1  0.04

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  38.0  22.0  0.00
1               2  1893-01-02  53.0   NaN  0.22
2               3  1893-01-03   NaN  13.0  0.73
3               4  1893-01-04  16.0   3.0  0.00
4               5  1893-01-05  27.0  13.0  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27   NaN   NaN   NaN
47112       47113  2021-12-28   NaN   NaN   NaN
47113       47114  2021-12-29   NaN   NaN   NaN
47114       47115  2021-12-30   NaN   NaN   NaN
47115       47116  2021-12-31   NaN   NaN   NaN

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1872-01-01   NaN   NaN  0.00
1               2  1872-01-02   NaN   NaN  0.00
2               3  1872-01-03   NaN   NaN  0.00
3               4  1872-01-04   NaN   NaN  0.66
4               5  1872-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
54782       54783  2021-12-27  34.0  22.1  0.00
54783       54784  2021-12-28  39.0  23.2  0.09
54784       54785  2021-12-29  37.0  28.2  0.02
54785       54786  2021-12-30  34.0  30.2  0.05
54786       54787  2021-12-31  37.9  32.0  0.01

[54787 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01   NaN   NaN  0.06
1               2  1871-01-02   NaN   NaN  0.00
2               3  1871-01-03   NaN   NaN  0.03
3               4  1871-01-04   NaN   NaN  0.00
4               5  1871-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  36.0  27.1  0.03
55148       55149  2021-12-28  41.0  32.0  0.09
55149       55150  2021-12-29  37.9  32.0  0.02
55150       55151  2021-12-30  41.0  35.1  0.00
55151       55152  2021-12-31  50.0  37.9  0.03

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1896-01-01  27.0  21.0  0.00
1               2  1896-01-02  40.0  20.0  0.00
2               3  1896-01-03  35.0  20.0  0.01
3               4  1896-01-04  20.0   8.0  0.00
4               5  1896-01-05  14.0   4.0  0.00
...           ...         ...   ...   ...   ...
46016       46017  2021-12-27  35.1  29.1  0.23
46017       46018  2021-12-28  39.0  34.0  0.24
46018       46019  2021-12-29  44.1  37.9  0.01
46019       46020  2021-12-30  48.0  41.0  0.01
46020       46021  2021-12-31  52.0  44.1  0.00

[46021 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1866-01-01  38.0  34.0  0.00
1               2  1866-01-02  36.0  34.0  0.50
2               3  1866-01-03  35.0  32.0  0.00
3               4  1866-01-04  34.0   NaN  0.00
4               5  1866-01-05   NaN  11.0  0.00
...           ...         ...   ...   ...   ...
56973       56974  2021-12-27  37.9  29.1  0.08
56974       56975  2021-12-28  46.0  35.1  0.01
56975       56976  2021-12-29  46.9  39.9  0.03
56976       56977  2021-12-30  51.1  42.1  0.17
56977       56978  2021-12-31  51.1  46.9  0.01

[56978 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1879-01-01  33.0  25.0  0.00
1               2  1879-01-02  29.0 -13.0  0.03
2               3  1879-01-03  -4.0 -20.0  0.00
3               4  1879-01-04   4.0 -10.0  0.00
4               5  1879-01-05   7.0  -6.0  0.00
...           ...         ...   ...   ...   ...
52225       52226  2021-12-27  64.9  39.9  0.20
52226       52227  2021-12-28  46.9  39.9  0.57
52227       52228  2021-12-29  48.9  41.0  0.00
52228       52229  2021-12-30  48.9  41.0  0.08
52229       52230  2021-12-31  57.9  42.1  0.00

[52230 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1898-01-01  21.0  15.0  0.00
1               2  1898-01-02  23.0   7.0  0.00
2               3  1898-01-03  35.0  23.0  0.00
3               4  1898-01-04  36.0  19.0  0.00
4               5  1898-01-05  42.0  20.0  0.00
...           ...         ...   ...   ...   ...
45285       45286  2021-12-27  50.0  35.1  0.53
45286       45287  2021-12-28  39.0  32.0  0.56
45287       45288  2021-12-29  37.0  33.1  0.00
45288       45289  2021-12-30  39.0  33.1  0.02
45289       45290  2021-12-31  50.0  39.0  0.00

[45290 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1864-01-01  31.0 -23.0  0.00
1               2  1864-01-02  -3.0 -22.0  0.00
2               3  1864-01-03  12.0  -8.0  0.00
3               4  1864-01-04  28.0  -2.0  0.00
4               5  1864-01-05  12.0   0.0  0.08
...           ...         ...   ...   ...   ...
57704       57705  2021-12-27  39.0  30.2  0.31
57705       57706  2021-12-28  36.0  30.2  0.17
57706       57707  2021-12-29  37.9  29.1  0.00
57707       57708  2021-12-30  34.0  27.1  0.00
57708       57709  2021-12-31  42.1  34.0  0.02

[57709 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1869-01-01  25.0  21.0  0.00
1               2  1869-01-02  30.0  22.0  0.50
2               3  1869-01-03  37.0  30.0  0.00
3               4  1869-01-04  35.0  22.0  0.03
4               5  1869-01-05  25.0  18.0  0.00
...           ...         ...   ...   ...   ...
55877       55878  2021-12-27  37.9  23.2  0.04
55878       55879  2021-12-28  34.0  21.2  0.29
55879       55880  2021-12-29  34.0  11.1  0.00
55880       55881  2021-12-30  30.2  10.2  0.01
55881       55882  2021-12-31  30.0  26.1  0.01

[55882 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01  38.0  25.0  0.00
1               2  1871-01-02  38.0  18.0  0.00
2               3  1871-01-03  22.0   3.0  0.00
3               4  1871-01-04  32.0   3.0  0.00
4               5  1871-01-05  35.0  21.0  0.08
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  42.1  30.2  0.27
55148       55149  2021-12-28  39.0  27.1  0.40
55149       55150  2021-12-29  37.9  26.2  0.00
55150       55151  2021-12-30  37.0  24.3  0.01
55151       55152  2021-12-31  37.9  32.0  0.04

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1897-01-01  40.0  34.0  0.00
1               2  1897-01-02  45.0  37.0  0.00
2               3  1897-01-03  57.0  40.0  4.90
3               4  1897-01-04  40.0  22.0  0.22
4               5  1897-01-05  25.0  19.0  0.23
...           ...         ...   ...   ...   ...
45650       45651  2021-12-27  42.1  31.1  0.27
45651       45652  2021-12-28  37.0  29.1  0.11
45652       45653  2021-12-29  39.0  30.2  0.02
45653       45654  2021-12-30  35.1  26.2  0.01
45654       45655  2021-12-31  39.9  33.1  0.02

[45655 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1883-01-01  20.0  12.0  0.05
1               2  1883-01-02  21.0   3.0  0.00
2               3  1883-01-03  21.0  14.0  0.00
3               4  1883-01-04  21.0  16.0  0.14
4               5  1883-01-05  26.0  20.0  0.00
...           ...         ...   ...   ...   ...
50764       50765  2021-12-27  55.0  35.1  0.00
50765       50766  2021-12-28  41.0  33.1  0.50
50766       50767  2021-12-29  37.9  28.2  0.01
50767       50768  2021-12-30  37.9  30.2  0.00
50768       50769  2021-12-31  55.0  28.0  0.00

[50769 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1898-01-01  19.0  -2.0  0.00
1               2  1898-01-02  22.0  10.0  0.01
2               3  1898-01-03  29.0  20.0   NaN
3               4  1898-01-04  32.0  16.0   NaN
4               5  1898-01-05  41.0  20.0   NaN
...           ...         ...   ...   ...   ...
45285       45286  2021-12-27  36.0  29.1  0.09
45286       45287  2021-12-28  34.0  27.1  0.06
45287       45288  2021-12-29  36.0  27.1  0.02
45288       45289  2021-12-30  33.1  26.1  0.12
45289       45290  2021-12-31  37.0  32.0  0.02

[45290 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1889-01-01  29.0  21.0  0.00
1               2  1889-01-02  35.0  23.0  0.00
2               3  1889-01-03  39.0  20.0  0.00
3               4  1889-01-04  37.0  32.0  0.00
4               5  1889-01-05  32.0  20.0  0.00
...           ...         ...   ...   ...   ...
48572       48573  2021-12-27  28.2  16.2  0.23
48573       48574  2021-12-28  30.2  25.2  0.05
48574       48575  2021-12-29  34.0  26.2  0.12
48575       48576  2021-12-30  28.2  17.2  0.00
48576       48577  2021-12-31  33.1  27.0  0.05

[48577 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  40.0  22.0   NaN
1               2  1894-01-02  48.0  31.0   NaN
2               3  1894-01-03  46.0  36.0   NaN
3               4  1894-01-04  49.0  31.0   NaN
4               5  1894-01-05  35.0  29.0  0.08
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27  45.0  34.0  0.43
46747       46748  2021-12-28  36.0  31.1  0.31
46748       46749  2021-12-29  37.9  31.1  0.00
46749       46750  2021-12-30  37.0  30.2  0.01
46750       46751  2021-12-31  48.9  36.0  0.00

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1874-01-01  40.0  36.0  0.00
1               2  1874-01-02  46.0  38.0  0.00
2               3  1874-01-03  60.0  45.0  0.00
3               4  1874-01-04  70.0  30.0  0.30
4               5  1874-01-05  31.0  27.0  0.00
...           ...         ...   ...   ...   ...
54051       54052  2021-12-27  48.0  33.1  0.10
54052       54053  2021-12-28  43.0  34.0  0.20
54053       54054  2021-12-29  42.1  36.0  0.03
54054       54055  2021-12-30  42.1  37.9  0.00
54055       54056  2021-12-31  50.0  39.0  0.12

[54056 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1879-01-01   NaN   NaN   NaN
1               2  1879-01-02   NaN   NaN   NaN
2               3  1879-01-03   NaN   NaN   NaN
3               4  1879-01-04   NaN   NaN   NaN
4               5  1879-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
52225       52226  2021-12-27  59.0  35.1  0.40
52226       52227  2021-12-28  53.1  37.9  0.29
52227       52228  2021-12-29  50.0  43.0  0.05
52228       52229  2021-12-30  55.9  44.1  0.04
52229       52230  2021-12-31  55.9  48.0  0.03

[52230 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1888-01-01  46.0  25.0   NaN
1               2  1888-01-02  27.0  19.0   NaN
2               3  1888-01-03  26.0  20.0   NaN
3               4  1888-01-04  41.0  19.0   NaN
4               5  1888-01-05  40.0  30.0   NaN
...           ...         ...   ...   ...   ...
48938       48939  2021-12-27  54.0  34.0  0.33
48939       48940  2021-12-28  45.0  35.1  0.37
48940       48941  2021-12-29  46.9  39.0  0.00
48941       48942  2021-12-30  46.9  37.9  0.04
48942       48943  2021-12-31  53.1  41.0  0.00

[48943 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1896-01-01  22.0   0.0  0.00

       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  45.0  25.0  0.00
1               2  1894-01-02  37.0  20.0  0.28
2               3  1894-01-03  25.0  14.0  0.00
3               4  1894-01-04  28.0   3.0  0.00
4               5  1894-01-05  18.0  -4.0  0.00
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27  20.1   4.1  0.01
46747       46748  2021-12-28  20.1   7.2  0.00
46748       46749  2021-12-29  18.1   8.2  0.01
46749       46750  2021-12-30  24.3  11.1  0.05
46750       46751  2021-12-31  19.0  10.0  0.05

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01   NaN   NaN   NaN
1               2  1893-01-02   NaN   NaN   NaN
2               3  1893-01-03   NaN   NaN   NaN
3               4  1893-01-04   NaN   NaN   NaN
4               5  1893-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  22.1  13.1  0.00
47112       47113  2021-12-28  24.3  16.2  0.07
47113       47114  2021-12-29  16.2   2.1  0.12
47114       47115  2021-12-30  34.0  10.2  0.23
47115       47116  2021-12-31  18.0  -7.1  0.07

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1882-01-01  42.0  35.0  0.12
1               2  1882-01-02  41.0  35.0  0.42
2               3  1882-01-03  35.0  26.0  0.17
3               4  1882-01-04  41.0  30.0  0.35
4               5  1882-01-05  41.0  35.0  0.22
...           ...         ...   ...   ...   ...
51129       51130  2021-12-27  21.2   9.1  0.01
51130       51131  2021-12-28  14.2   4.1  0.00
51131       51132  2021-12-29  15.3   5.2  0.04
51132       51133  2021-12-30  14.2   9.1  0.18
51133       51134  2021-12-31  18.0   1.9  0.00

[51134 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01  33.0  22.0  0.00
1               2  1895-01-02  25.0  20.0  0.08
2               3  1895-01-03  25.0  18.0  0.06
3               4  1895-01-04  31.0  21.0  0.00
4               5  1895-01-05  44.0  30.0  0.00
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  22.1  14.2  0.00
46382       46383  2021-12-28  21.2  14.2  0.01
46383       46384  2021-12-29  24.3  16.2  0.00
46384       46385  2021-12-30  24.1  17.1  0.09
46385       46386  2021-12-31  24.1  -5.1  0.00

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1887-01-01  54.0  49.0  0.02
1               2  1887-01-02  55.0  47.0  0.03
2               3  1887-01-03  59.0  45.0  0.01
3               4  1887-01-04  58.0  40.0  0.03
4               5  1887-01-05  55.0  46.0  0.00
...           ...         ...   ...   ...   ...
49303       49304  2021-12-27  44.1  36.0  0.16
49304       49305  2021-12-28  48.9  37.0  0.16
49305       49306  2021-12-29  50.0  34.0  0.21
49306       49307  2021-12-30  48.9  34.0  0.13
49307       49308  2021-12-31  48.9  33.1  0.07

[49308 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01   NaN   NaN  0.00
1               2  1893-01-02   NaN   NaN  0.00
2               3  1893-01-03   NaN   NaN  0.00
3               4  1893-01-04   NaN   NaN  0.00
4               5  1893-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  34.0  22.1  0.06
47112       47113  2021-12-28  36.0  32.0  0.12
47113       47114  2021-12-29  37.0  28.2  0.03
47114       47115  2021-12-30  43.0  32.0  0.14
47115       47116  2021-12-31  44.1  30.9  0.04

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  48.0  35.0  0.00
1               2  1893-01-02  44.0  31.0  0.00
2               3  1893-01-03  43.0  37.0  0.00
3               4  1893-01-04  44.0  31.0  0.00
4               5  1893-01-05  42.0  32.0  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  34.0  29.1  0.03
47112       47113  2021-12-28  37.0  33.1  0.02
47113       47114  2021-12-29  36.0  30.2  0.00
47114       47115  2021-12-30   NaN   NaN   NaN
47115       47116  2021-12-31  43.0  26.1  0.01

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  40.0  36.0  0.13
1               2  1894-01-02  40.0  35.0  0.00
2               3  1894-01-03  38.0  30.0  0.04
3               4  1894-01-04  36.0  28.0  0.06
4               5  1894-01-05  37.0  22.0  0.01
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27  27.1  17.2  0.03
46747       46748  2021-12-28  28.2  24.3   NaN
46748       46749  2021-12-29  29.1  22.1  0.13
46749       46750  2021-12-30   NaN   NaN   NaN
46750       46751  2021-12-31  30.9  21.9  0.00

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  59.0  35.0   NaN
1               2  1893-01-02  55.0  31.0   NaN
2               3  1893-01-03  57.0  28.0   NaN
3               4  1893-01-04  55.0  32.0   NaN
4               5  1893-01-05  48.0  38.0   NaN
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  51.1  35.1  0.00
47112       47113  2021-12-28  39.0  36.0  0.14
47113       47114  2021-12-29  45.0  32.0  0.13
47114       47115  2021-12-30   NaN   NaN   NaN
47115       47116  2021-12-31  53.1  28.9  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01  49.0  34.0  0.67
1               2  1895-01-02  54.0  44.0  0.69
2               3  1895-01-03  56.0  49.0   NaN
3               4  1895-01-04  53.0  48.0  0.40
4               5  1895-01-05  50.0  44.0  0.36
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  43.0  35.1  0.16
46382       46383  2021-12-28  46.0  36.0  0.38
46383       46384  2021-12-29  48.9  35.1  0.08
46384       46385  2021-12-30  45.0  35.1  0.20
46385       46386  2021-12-31  48.0  33.1  0.12

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  50.0  41.0  0.65
1               2  1893-01-02  52.0  29.0  0.00
2               3  1893-01-03  57.0  34.0  0.00
3               4  1893-01-04  55.0  31.0   NaN
4               5  1893-01-05  55.0  32.0   NaN
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  73.9  57.0  0.00
47112       47113  2021-12-28  75.9  46.9  0.00
47113       47114  2021-12-29  57.9  43.0  0.22
47114       47115  2021-12-30  66.0  50.0  0.00
47115       47116  2021-12-31  73.0  50.0  1.38

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01  33.0   5.0  0.00
1               2  1895-01-02  38.0   6.0  0.00
2               3  1895-01-03  43.0  17.0  0.00
3               4  1895-01-04  55.0  10.0  0.00
4               5  1895-01-05  48.0  38.0  0.00
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  39.0  22.1  0.00
46382       46383  2021-12-28  48.9  17.2  0.00
46383       46384  2021-12-29  48.9   8.2  0.00
46384       46385  2021-12-30  52.0  31.1  0.00
46385       46386  2021-12-31  51.1  21.9  0.02

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1889-01-01  46.0   5.0   0.0
1               2  1889-01-02  48.0   5.0   0.0
2               3  1889-01-03  48.0   8.0   0.0
3               4  1889-01-04  40.0   5.0   0.0
4               5  1889-01-05  40.0  18.0   0.0
...           ...         ...   ...   ...   ...
48572       48573  2021-12-27  45.0  17.2   0.0
48573       48574  2021-12-28  44.1  18.1   0.0
48574       48575  2021-12-29  48.9   5.2   0.0
48575       48576  2021-12-30  55.0  16.2   0.0
48576       48577  2021-12-31  55.9  19.0   0.0

[48577 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1878-01-01  60.0  38.0  0.00
1               2  1878-01-02  58.0  37.0  0.00
2               3  1878-01-03  61.0  37.0  0.00
3               4  1878-01-04  63.0  38.0  0.00
4               5  1878-01-05  67.0  48.0  0.00
...           ...         ...   ...   ...   ...
52590       52591  2021-12-27  55.0  42.1  0.24
52591       52592  2021-12-28  55.0  42.1  0.00
52592       52593  2021-12-29  53.1  46.0  1.74
52593       52594  2021-12-30  55.0  51.1  2.57
52594       52595  2021-12-31  59.0  45.0  0.00

[52595 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1882-01-01   NaN   NaN  0.00
1               2  1882-01-02   NaN   NaN  0.00
2               3  1882-01-03   NaN   NaN  0.00
3               4  1882-01-04   NaN   NaN  0.15
4               5  1882-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
51129       51130  2021-12-27  48.9  42.1  0.29
51130       51131  2021-12-28  46.9  39.0  0.01
51131       51132  2021-12-29  52.0  37.9  0.21
51132       51133  2021-12-30  52.0  39.9  0.00
51133       51134  2021-12-31  50.0  37.9  0.00

[51134 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01   NaN   NaN  0.00
1               2  1871-01-02   NaN   NaN  0.00
2               3  1871-01-03   NaN   NaN  0.00
3               4  1871-01-04   NaN   NaN  0.00
4               5  1871-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  43.0  36.0  0.03
55148       55149  2021-12-28  57.0  36.0  0.05
55149       55150  2021-12-29  52.0  46.0  0.02
55150       55151  2021-12-30  53.1  48.0  0.26
55151       55152  2021-12-31  57.0  48.9  0.01

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  62.0  38.0  0.53
1               2  1893-01-02  48.0  44.0  0.00
2               3  1893-01-03  44.0  36.0  0.16
3               4  1893-01-04  38.0  29.0  0.07
4               5  1893-01-05  38.0   NaN  0.21
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  72.0  52.0  0.00
47112       47113  2021-12-28  68.0  61.0  0.00
47113       47114  2021-12-29  72.0  66.0  0.00
47114       47115  2021-12-30  73.0  59.0  0.02
47115       47116  2021-12-31  68.0  57.9  0.17

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01  61.0  49.0  0.55
1               2  1893-01-02  55.0  36.0  0.00
2               3  1893-01-03  58.0  38.0  0.00
3               4  1893-01-04  64.0  36.0  0.00
4               5  1893-01-05  61.0   NaN  0.00
...           ...         ...   ...   ...   ...
47111       47112  2021-12-27  78.1  54.0  0.00
47112       47113  2021-12-28  75.9  61.0  0.00
47113       47114  2021-12-29  75.9  61.0  0.00
47114       47115  2021-12-30  82.0  72.0  0.02
47115       47116  2021-12-31  81.0  71.1  0.00

[47116 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1871-01-01   NaN   NaN  0.00
1               2  1871-01-02   NaN   NaN  0.00
2               3  1871-01-03   NaN   NaN  0.00
3               4  1871-01-04   NaN   NaN  0.00
4               5  1871-01-05   NaN   NaN  0.00
...           ...         ...   ...   ...   ...
55147       55148  2021-12-27  72.0  48.9  0.01
55148       55149  2021-12-28  53.1  42.1  0.51
55149       55150  2021-12-29  53.1  44.1  0.01
55150       55151  2021-12-30  50.0  43.0  0.02
55151       55152  2021-12-31   NaN   NaN   NaN

[55152 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  42.0  25.0  0.00
1               2  1894-01-02  49.0  35.0  0.00
2               3  1894-01-03  52.0  38.0  0.00
3               4  1894-01-04  59.0  51.0  0.00
4               5  1894-01-05  58.0  38.0  0.56
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27  66.0  43.0  0.22
46747       46748  2021-12-28  46.9  39.9  0.66
46748       46749  2021-12-29  46.9  41.0  0.00
46749       46750  2021-12-30  48.0  39.9  0.17
46750       46751  2021-12-31  57.9  44.1  0.03

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1897-01-01  62.0  55.0  0.03
1               2  1897-01-02  66.0  56.0  0.21
2               3  1897-01-03  64.0  26.0  0.35
3               4  1897-01-04  36.0  20.0  0.62
4               5  1897-01-05  23.0  17.0  0.00
...           ...         ...   ...   ...   ...
45650       45651  2021-12-27  72.0  48.0  0.00
45651       45652  2021-12-28  66.0  43.0  0.48
45652       45653  2021-12-29  51.1  39.0  0.09
45653       45654  2021-12-30  48.9  44.1  0.00
45654       45655  2021-12-31  66.0  48.9  0.21

[45655 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1872-01-01  43.0  37.0  0.00
1               2  1872-01-02  43.0  34.0  0.00
2               3  1872-01-03  40.0  36.0  0.09
3               4  1872-01-04  35.0  24.0  0.00
4               5  1872-01-05  43.0  32.0  0.00
...           ...         ...   ...   ...   ...
54782       54783  2021-12-27  64.0  41.0  0.20
54783       54784  2021-12-28  43.0  37.9  0.89
54784       54785  2021-12-29  44.1  37.9  0.01
54785       54786  2021-12-30  48.0  37.0  0.02
54786       54787  2021-12-31  61.0  37.9  0.14

[54787 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1873-01-01  39.0  34.0  0.01
1               2  1873-01-02  53.0  38.0  0.39
2               3  1873-01-03  52.0  36.0  0.01
3               4  1873-01-04  35.0  27.0  0.00
4               5  1873-01-05  35.0  27.0  0.24
...           ...         ...   ...   ...   ...
54416       54417  2021-12-27  68.0  51.1  0.10
54417       54418  2021-12-28  66.9  43.0  0.20
54418       54419  2021-12-29  59.0  48.0  0.08
54419       54420  2021-12-30  54.0  43.0  0.00
54420       54421  2021-12-31  64.0  39.9  0.14

[54421 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1873-01-01  45.0  34.0  0.06
1               2  1873-01-02  55.0  36.0  0.22
2               3  1873-01-03  49.0  37.0  0.00
3               4  1873-01-04  35.0  29.0  0.00
4               5  1873-01-05  36.0  27.0  0.15
...           ...         ...   ...   ...   ...
54416       54417  2021-12-27  73.9  54.0  0.01
54417       54418  2021-12-28  70.0  43.0  0.30
54418       54419  2021-12-29  57.0  48.9  0.24
54419       54420  2021-12-30  54.0  48.0  0.00
54420       54421  2021-12-31  68.0  48.0  0.15

[54421 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1880-01-01  46.0  28.0  0.00
1               2  1880-01-02  48.0  43.0  0.45
2               3  1880-01-03  63.0  47.0  0.03
3               4  1880-01-04  58.0  46.0  0.45
4               5  1880-01-05  58.0  44.0  0.16
...           ...         ...   ...   ...   ...
51860       51861  2021-12-27  59.0  36.0  0.00
51861       51862  2021-12-28  46.0  37.0  0.65
51862       51863  2021-12-29  45.0  31.1  0.03
51863       51864  2021-12-30  42.1  31.1  0.04
51864       51865  2021-12-31  57.0  37.9  0.01

[51865 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1896-01-01  29.0  17.0   NaN
1               2  1896-01-02  43.0  19.0  0.20
2               3  1896-01-03  21.0   9.0  0.12
3               4  1896-01-04   8.0  -2.0  0.00
4               5  1896-01-05  14.0   4.0  0.00
...           ...         ...   ...   ...   ...
46016       46017  2021-12-27  64.0  39.9  0.38
46017       46018  2021-12-28  52.0  39.9  0.37
46018       46019  2021-12-29  50.0  43.0  0.02
46019       46020  2021-12-30  52.0  43.0  0.02
46020       46021  2021-12-31  55.9  46.0  0.01

[46021 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1892-01-01  65.0   NaN   NaN
1               2  1892-01-02   NaN   NaN   NaN
2               3  1892-01-03   NaN  26.0   NaN
3               4  1892-01-04   NaN   NaN   NaN
4               5  1892-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
47477       47478  2021-12-27  73.9  55.0  0.00
47478       47479  2021-12-28  78.1  64.0  0.00
47479       47480  2021-12-29  73.0  66.0  1.51
47480       47481  2021-12-30  78.1  64.0  0.29
47481       47482  2021-12-31  80.1  63.0  0.00

[47482 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  54.0  31.0  0.00
1               2  1894-01-02  64.0   NaN  0.00
2               3  1894-01-03   NaN  34.0  0.00
3               4  1894-01-04  66.0  60.0  0.07
4               5  1894-01-05  70.0  60.0  0.00
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27  75.0  63.0  0.00
46747       46748  2021-12-28  75.9  68.0  0.29
46748       46749  2021-12-29  78.1  69.1  0.28
46749       46750  2021-12-30  79.0  71.1  0.00
46750       46751  2021-12-31  78.1  70.0  0.00

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1885-01-01   NaN   NaN   NaN
1               2  1885-01-02   NaN   NaN   NaN
2               3  1885-01-03   NaN   NaN   NaN
3               4  1885-01-04   NaN   NaN   NaN
4               5  1885-01-05   NaN   NaN   NaN
...           ...         ...   ...   ...   ...
50033       50034  2021-12-27  78.1  64.0  0.00
50034       50035  2021-12-28  73.9  63.0  0.05
50035       50036  2021-12-29  72.0  51.1  0.30
50036       50037  2021-12-30  70.0  46.9  0.00
50037       50038  2021-12-31  73.0  57.0  0.00

[50038 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  30.0  -3.0   NaN
1               2  1894-01-02   6.0 -12.0   NaN
2               3  1894-01-03   7.0 -15.0   NaN
3               4  1894-01-04  13.0 -24.0   NaN
4               5  1894-01-05   2.0 -31.0   NaN
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27 -10.8 -21.8  0.01
46747       46748  2021-12-28 -12.8 -22.9  0.00
46748       46749  2021-12-29  -9.8 -20.7  0.00
46749       46750  2021-12-30  -2.7 -17.9  0.01
46750       46751  2021-12-31 -13.0 -25.1  0.00

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1880-01-01  38.0  28.0  0.00
1               2  1880-01-02  45.0   5.0  0.00
2               3  1880-01-03  34.0   6.0  0.00
3               4  1880-01-04  43.0 -10.0  0.00
4               5  1880-01-05 -10.0 -19.0  0.00
...           ...         ...   ...   ...   ...
51860       51861  2021-12-27 -11.7 -25.8  0.00
51861       51862  2021-12-28  -3.8 -32.8  0.00
51862       51863  2021-12-29  -3.8 -27.8  0.00
51863       51864  2021-12-30   3.2 -17.9  0.04
51864       51865  2021-12-31  -6.0 -23.1  0.00

[51865 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1894-01-01  32.0  10.0   0.0
1               2  1894-01-02  -6.0 -12.0   0.0
2               3  1894-01-03   0.0 -20.0   0.0
3               4  1894-01-04   6.0 -14.0   0.0
4               5  1894-01-05  -7.0 -18.0   0.0
...           ...         ...   ...   ...   ...
46746       46747  2021-12-27   NaN   NaN   NaN
46747       46748  2021-12-28   NaN   NaN   NaN
46748       46749  2021-12-29   NaN   NaN   NaN
46749       46750  2021-12-30   NaN   NaN   NaN
46750       46751  2021-12-31   NaN   NaN   NaN

[46751 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1895-01-01   NaN   NaN   0.0
1               2  1895-01-02   NaN   NaN   0.0
2               3  1895-01-03   NaN   NaN   0.0
3               4  1895-01-04   NaN   NaN   0.1
4               5  1895-01-05   NaN   NaN   0.0
...           ...         ...   ...   ...   ...
46381       46382  2021-12-27  46.0  16.2   0.0
46382       46383  2021-12-28  36.0  17.2   0.0
46383       46384  2021-12-29  30.2   8.2   0.0
46384       46385  2021-12-30  54.0   3.0   0.0
46385       46386  2021-12-31  30.0   8.1   0.0

[46386 rows x 5 columns]
       Unnamed: 0        Date  tmax  tmin  prcp
0               1  1893-01-01   NaN   NaN  0.00

In [7]:
def NewCol(x):
    x['id'] = "{}".format(x) 
    return x

In [8]:
USC00042863

In [9]:
USW00014929.isna().sum()

Unnamed: 0      0
Date            0
tmax          551
tmin          587
prcp          687
dtype: int64

In [10]:
USW00014925.isna().sum()

Unnamed: 0        0
Date              0
tmax           9558
tmin           9590
prcp          10109
dtype: int64

In [11]:
for file in sheets:
    exec('file = file.dropna()')

In [12]:
%whos

Variable      Type         Data/Info
------------------------------------
NewCol        function     <function NewCol at 0x7fd22ea76c10>
USC00042863   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USC00166584   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USC00280734   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USC00286055   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USC00356749   DataFrame           Unnamed: 0        <...>n[53691 rows x 5 columns]
USC00380072   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00003017   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00003103   DataFrame           Unnamed: 0        <...>n[44925 rows x 5 columns]
USW00003145   DataFrame           Unnamed: 0        <...>n[53326 rows x 5 columns]
USW00003171   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00003812   DataFrame           Unnamed: 0        <...>n[55517 rows x 5 columns]
USW00003813   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00003820   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00003822   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00003856   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00003859   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00003860   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00003872   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00003904   DataFrame           Unnamed: 0        <...>n[50769 rows x 5 columns]
USW00003927   DataFrame           Unnamed: 0        <...>n[44925 rows x 5 columns]
USW00003937   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00003940   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00003945   DataFrame           Unnamed: 0        <...>n[48212 rows x 5 columns]
USW00003947   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00003953   DataFrame           Unnamed: 0        <...>n[47847 rows x 5 columns]
USW00003963   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00003965   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00004853   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00012815   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00012816   DataFrame           Unnamed: 0        <...>n[47847 rows x 5 columns]
USW00012835   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00012836   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00012839   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00012842   DataFrame           Unnamed: 0        <...>n[47847 rows x 5 columns]
USW00012844   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00012921   DataFrame           Unnamed: 0        <...>n[49673 rows x 5 columns]
USW00012923   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00012924   DataFrame           Unnamed: 0        <...>n[48943 rows x 5 columns]
USW00012960   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00013722   DataFrame           Unnamed: 0        <...>n[49308 rows x 5 columns]
USW00013733   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013736   DataFrame           Unnamed: 0        <...>n[54421 rows x 5 columns]
USW00013737   DataFrame           Unnamed: 0        <...>n[54056 rows x 5 columns]
USW00013739   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00013740   DataFrame           Unnamed: 0        <...>n[49308 rows x 5 columns]
USW00013743   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00013781   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00013833   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013838   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00013865   DataFrame           Unnamed: 0        <...>n[48212 rows x 5 columns]
USW00013866   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013873   DataFrame           Unnamed: 0        <...>n[59900 rows x 5 columns]
USW00013874   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00013876   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00013881   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00013882   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00013883   DataFrame           Unnamed: 0        <...>n[48943 rows x 5 columns]
USW00013886   DataFrame           Unnamed: 0        <...>n[50038 rows x 5 columns]
USW00013889   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00013893   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00013895   DataFrame           Unnamed: 0        <...>n[54421 rows x 5 columns]
USW00013896   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013897   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00013899   DataFrame           Unnamed: 0        <...>n[51865 rows x 5 columns]
USW00013942   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013957   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00013958   DataFrame           Unnamed: 0        <...>n[45290 rows x 5 columns]
USW00013962   DataFrame           Unnamed: 0        <...>n[49673 rows x 5 columns]
USW00013963   DataFrame           Unnamed: 0        <...>n[53326 rows x 5 columns]
USW00013964   DataFrame           Unnamed: 0        <...>n[50769 rows x 5 columns]
USW00013967   DataFrame           Unnamed: 0        <...>n[47847 rows x 5 columns]
USW00013968   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00013970   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013971   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00013984   DataFrame           Unnamed: 0        <...>n[49673 rows x 5 columns]
USW00013985   DataFrame           Unnamed: 0        <...>n[53691 rows x 5 columns]
USW00013994   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00013995   DataFrame           Unnamed: 0        <...>n[48943 rows x 5 columns]
USW00013996   DataFrame           Unnamed: 0        <...>n[48943 rows x 5 columns]
USW00014710   DataFrame           Unnamed: 0        <...>n[49673 rows x 5 columns]
USW00014711   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00014733   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00014735   DataFrame           Unnamed: 0        <...>n[54056 rows x 5 columns]
USW00014739   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00014742   DataFrame           Unnamed: 0        <...>n[50404 rows x 5 columns]
USW00014745   DataFrame           Unnamed: 0        <...>n[56248 rows x 5 columns]
USW00014750   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00014753   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00014764   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00014768   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00014778   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00014792   DataFrame           Unnamed: 0        <...>n[56978 rows x 5 columns]
USW00014821   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00014827   DataFrame           Unnamed: 0        <...>n[45290 rows x 5 columns]
USW00014836   DataFrame           Unnamed: 0        <...>n[57709 rows x 5 columns]
USW00014837   DataFrame           Unnamed: 0        <...>n[55882 rows x 5 columns]
USW00014839   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00014840   DataFrame           Unnamed: 0        <...>n[45655 rows x 5 columns]
USW00014842   DataFrame           Unnamed: 0        <...>n[50769 rows x 5 columns]
USW00014845   DataFrame           Unnamed: 0        <...>n[45290 rows x 5 columns]
USW00014847   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00014848   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00014860   DataFrame           Unnamed: 0        <...>n[54056 rows x 5 columns]
USW00014894   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00014895   DataFrame           Unnamed: 0        <...>n[48943 rows x 5 columns]
USW00014897   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00014898   DataFrame           Unnamed: 0        <...>n[45655 rows x 5 columns]
USW00014913   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00014914   DataFrame           Unnamed: 0        <...>n[51499 rows x 5 columns]
USW00014916   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00014918   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]

USW00014920   DataFrame           Unnamed: 0        <...>n[54421 rows x 5 columns]
USW00014922   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00014923   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00014925   DataFrame           Unnamed: 0        <...>n[49308 rows x 5 columns]
USW00014926   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00014929   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00014933   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00014935   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00014936   DataFrame           Unnamed: 0        <...>n[51134 rows x 5 columns]
USW00014939   DataFrame           Unnamed: 0        <...>n[49308 rows x 5 columns]
USW00014941   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00014942   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00014943   DataFrame           Unnamed: 0        <...>n[48212 rows x 5 columns]
USW00014944   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00014972   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00014990   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00014991   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00023009   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00023044   DataFrame           Unnamed: 0        <...>n[52230 rows x 5 columns]
USW00023047   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00023050   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00023051   DataFrame           Unnamed: 0        <...>n[45655 rows x 5 columns]
USW00023065   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00023066   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00023154   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00023155   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00023160   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00023179   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00023183   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00023185   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00023188   DataFrame           Unnamed: 0        <...>n[62457 rows x 5 columns]
USW00023271   DataFrame           Unnamed: 0        <...>n[52595 rows x 5 columns]
USW00023275   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00024011   DataFrame           Unnamed: 0        <...>n[53691 rows x 5 columns]
USW00024018   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00024021   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00024023   DataFrame           Unnamed: 0        <...>n[53691 rows x 5 columns]
USW00024028   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00024032   DataFrame           Unnamed: 0        <...>n[48212 rows x 5 columns]
USW00024121   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00024127   DataFrame           Unnamed: 0        <...>n[53691 rows x 5 columns]
USW00024128   DataFrame           Unnamed: 0        <...>n[52595 rows x 5 columns]
USW00024131   DataFrame           Unnamed: 0        <...>n[53691 rows x 5 columns]
USW00024143   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00024144   DataFrame           Unnamed: 0        <...>n[51499 rows x 5 columns]
USW00024149   DataFrame           Unnamed: 0        <...>n[51134 rows x 5 columns]
USW00024153   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00024155   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00024157   DataFrame           Unnamed: 0        <...>n[51134 rows x 5 columns]
USW00024163   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00024213   DataFrame           Unnamed: 0        <...>n[49308 rows x 5 columns]
USW00024221   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00024232   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00024233   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00024257   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00024286   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00053920   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00093037   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00093058   DataFrame           Unnamed: 0        <...>n[48577 rows x 5 columns]
USW00093134   DataFrame           Unnamed: 0        <...>n[52595 rows x 5 columns]
USW00093193   DataFrame           Unnamed: 0        <...>n[51134 rows x 5 columns]
USW00093721   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00093729   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00093805   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00093812   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00093815   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00093817   DataFrame           Unnamed: 0        <...>n[45655 rows x 5 columns]
USW00093819   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00093820   DataFrame           Unnamed: 0        <...>n[54421 rows x 5 columns]
USW00093821   DataFrame           Unnamed: 0        <...>n[54421 rows x 5 columns]
USW00093822   DataFrame           Unnamed: 0        <...>n[51865 rows x 5 columns]
USW00093824   DataFrame           Unnamed: 0        <...>n[46021 rows x 5 columns]
USW00093842   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00093874   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00093988   DataFrame           Unnamed: 0        <...>n[50038 rows x 5 columns]
USW00094008   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00094012   DataFrame           Unnamed: 0        <...>n[51865 rows x 5 columns]
USW00094014   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00094040   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00094129   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00094224   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00094236   DataFrame           Unnamed: 0        <...>n[45290 rows x 5 columns]
USW00094298   DataFrame           Unnamed: 0        <...>n[60631 rows x 5 columns]
USW00094728   DataFrame           Unnamed: 0        <...>n[55882 rows x 5 columns]
USW00094746   DataFrame           Unnamed: 0        <...>n[47482 rows x 5 columns]
USW00094815   DataFrame           Unnamed: 0        <...>n[48943 rows x 5 columns]
USW00094822   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00094823   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00094830   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00094846   DataFrame           Unnamed: 0        <...>n[55152 rows x 5 columns]
USW00094847   DataFrame           Unnamed: 0        <...>n[54056 rows x 5 columns]
USW00094850   DataFrame           Unnamed: 0        <...>n[54787 rows x 5 columns]
USW00094860   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00094908   DataFrame           Unnamed: 0        <...>n[54056 rows x 5 columns]
USW00094910   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00094929   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
USW00094949   DataFrame           Unnamed: 0        <...>n[46386 rows x 5 columns]
USW00094950   DataFrame           Unnamed: 0        <...>n[47116 rows x 5 columns]
USW00094973   DataFrame           Unnamed: 0        <...>n[46751 rows x 5 columns]
city_info     DataFrame         Unnamed: 0        Na<...>n\n[461 rows x 8 columns]
file          str          USC00042863.csv
filelist      list         n=211
folder        str          /home/jibo16/Desktop/Herm<...>p/PrecipMap/Datak/7890488
folium        module       <module 'folium' from '/h<...>ages/folium/__init__.py'>
os            module       <module 'os' from '/usr/lib/python3.9/os.py'>
pd            module       <module 'pandas' from '/h<...>ages/pandas/__init__.py'>
sheets        list         n=0
var           str          sheets

In [13]:
city_info